// ----------------Centralized Application Constants------------

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ASSOCIATION_ADMIN: 'ASSOCIATION_ADMIN',
  RESIDENT: 'RESIDENT',
  EMPLOYEE: 'EMPLOYEE',
};

const MEMBERSHIP_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  PAST: 'PAST',
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

module.exports = {
  ROLES,
  MEMBERSHIP_STATUS,
  HTTP_STATUS,
};
